apiVersion: v1
kind: Pod
metadata:
  name: git-sync-with-gce-node-auth
spec:
  containers:
    - name: git-sync
      # Need the version support GIT_SYNC_AUTH_URL
      image: k8s.gcr.io/git-sync:latest
      imagePullPolicy: Always
      args:
        - --v=2
      env:
        - name: GIT_SYNC_REPO
          value: https://source.developers.google.com/p/$PROJECT/r/$REPO_NAME
        - name: GIT_SYNC_DEST
          value: git-data
        - name: GIT_SYNC_AUTH_URL
          value: http://localhost:9102/auth_callback
    - name: gce-node-auth
      image: gcr.io/$PROJECT/gce-node-auth:latest
      imagePullPolicy: Always
